In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [13]:
### sentences
sent=[
    "this movie is great and entertaining",
    "this movie is phenomenol and mustwatch",
    "the plot was boring and predictable",
    "a masterpiece in cinema",
    "waste of time and money",
    "highly recommend this movie",
    "worst film i have ever seen",
    "wonderful story and great direction"
]

In [14]:
vocab_size = 10000

In [15]:
one_hot_en = [one_hot(words,vocab_size) for words in sent]

one_hot_en

[[9209, 2618, 8540, 3646, 2622, 4928],
 [9209, 2618, 8540, 4308, 2622, 174],
 [8019, 5734, 3544, 7900, 2622, 3108],
 [5960, 3118, 6629, 2436],
 [3521, 6855, 5309, 2622, 2637],
 [7422, 2079, 9209, 2618],
 [7129, 575, 2888, 7929, 5673, 7102],
 [5876, 6958, 2622, 3646, 1036]]

In [ ]:
from tensorflow.keras.layers import  Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [17]:
import numpy as np

In [18]:
set_length=8

In [22]:
embedded = pad_sequences(one_hot_en,padding='pre',maxlen=set_length)

embedded

array([[   0,    0, 9209, 2618, 8540, 3646, 2622, 4928],
       [   0,    0, 9209, 2618, 8540, 4308, 2622,  174],
       [   0,    0, 8019, 5734, 3544, 7900, 2622, 3108],
       [   0,    0,    0,    0, 5960, 3118, 6629, 2436],
       [   0,    0,    0, 3521, 6855, 5309, 2622, 2637],
       [   0,    0,    0,    0, 7422, 2079, 9209, 2618],
       [   0,    0, 7129,  575, 2888, 7929, 5673, 7102],
       [   0,    0,    0, 5876, 6958, 2622, 3646, 1036]])

In [23]:
# Feature representation
dim=10

In [24]:
model=Sequential()

model.add(Embedding(vocab_size,dim,input_length=set_length))
model.compile('adam','mse')

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [26]:
model.predict(embedded)

1/1 [==============================] - 0s 453ms/step


array([[[ 0.02890183, -0.04501071,  0.04605417, -0.01318548,
         -0.04230002,  0.0077008 , -0.04570052,  0.04958418,
         -0.04911208, -0.04967723],
        [ 0.02890183, -0.04501071,  0.04605417, -0.01318548,
         -0.04230002,  0.0077008 , -0.04570052,  0.04958418,
         -0.04911208, -0.04967723],
        [ 0.01596073, -0.03356172, -0.04784137, -0.00827371,
          0.00347652,  0.01254622, -0.03104665, -0.024863  ,
          0.01608627, -0.01850554],
        [ 0.03861484,  0.0240241 , -0.04860988,  0.0127787 ,
          0.0269936 , -0.04225897, -0.0056914 , -0.02348318,
          0.0076769 , -0.01374924],
        [-0.01507686,  0.01740898, -0.02660546,  0.02466956,
         -0.00206512, -0.02008668, -0.02945354,  0.03492552,
          0.00063214,  0.03958037],
        [-0.00767727, -0.00347917,  0.04902575,  0.02099279,
         -0.02798449, -0.02812641, -0.02421049,  0.0275362 ,
          0.03066799,  0.01959193],
        [ 0.03860511, -0.00834436,  0.01375676, -0.0

In [31]:
embedded[0]

array([   0,    0, 9209, 2618, 8540, 3646, 2622, 4928])

In [30]:
model.predict(embedded[0])

1/1 [==============================] - 0s 32ms/step


array([[ 0.02890183, -0.04501071,  0.04605417, -0.01318548, -0.04230002,
         0.0077008 , -0.04570052,  0.04958418, -0.04911208, -0.04967723],
       [ 0.02890183, -0.04501071,  0.04605417, -0.01318548, -0.04230002,
         0.0077008 , -0.04570052,  0.04958418, -0.04911208, -0.04967723],
       [ 0.01596073, -0.03356172, -0.04784137, -0.00827371,  0.00347652,
         0.01254622, -0.03104665, -0.024863  ,  0.01608627, -0.01850554],
       [ 0.03861484,  0.0240241 , -0.04860988,  0.0127787 ,  0.0269936 ,
        -0.04225897, -0.0056914 , -0.02348318,  0.0076769 , -0.01374924],
       [-0.01507686,  0.01740898, -0.02660546,  0.02466956, -0.00206512,
        -0.02008668, -0.02945354,  0.03492552,  0.00063214,  0.03958037],
       [-0.00767727, -0.00347917,  0.04902575,  0.02099279, -0.02798449,
        -0.02812641, -0.02421049,  0.0275362 ,  0.03066799,  0.01959193],
       [ 0.03860511, -0.00834436,  0.01375676, -0.03322598, -0.02906637,
         0.02922647, -0.04653441,  0.04549019